### ISSUE TITLE
100% coverage reported incorrectly

### ISSUE THREAD

**Issue by jedireza** [nlf/lab-babel#9]
I'm working with `lab-babel` in a larger project and suspected some incorrect coverage reported. To demonstrate I updated the [jedireza/lab-es6](https://github.com/jedireza/lab-es6) example.

You just need to clone it, `npm install` and then `npm test`.

It shouldn't be 100% covered because I never tested the `subtractSomething` function.

**Comment by jedireza** [comment]
Possibly related to: https://github.com/hapijs/lab/issues/459

**Comment by willin** [comment]
i met the same problem

**Comment by mitch000001** [comment]
Same here. Seems like the `auxiliaryCommentBefore` and `auxiliaryCommentAfter` in https://github.com/nlf/lab-babel/blob/master/lib/index.js#L14-L15 are responsible for that. Removing these two lines brings back proper code coverage.
Actually I don't know why they were introduced in the first place so I hesitate to open a PR. Maybe @phated can clarify why they are/were needed.

**Comment by phated** [comment]
All the context needed should be in https://github.com/nlf/lab-babel/pull/4

Lab doesn't (or at least didn't) have a way to "skip next line" the way that istanbul did, so each line of generated code needed to be wrapped in a before & after comment.  If lab has updated to allow comment to "skip next line" that would be ideal to use; however, I've stopped using lab since they don't support older versions of node.

**Comment by jedireza** [comment]
`lab@11.x` is out and has a fix in place for this now (https://github.com/hapijs/lab/pull/622).
